language: c++
sudo: false
dist: bionic

branches:
  except: /pr\/.*/

compiler:
  - gcc-8
  - clang-10

os:
  - linux
  - osx

arch:
  - amd64

addons:
  apt:
    update: true
    packages:
      - clang
      - cmake
      - gnuplot
      - gcc

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir build
  - cd $TRAVIS_BUILD_DIR/build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake --build .
  - DESTDIR=./install cmake -DCMAKE_INSTALL_PREFIX=/ -P ./cmake_install.cmake

after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - ./install/lab1/lab1 --dump-data -od test
  - |
    for file in ./install/lab1/output/*.txt; do
      diff "$filename" "test/$(basename $filename)"
    done
