language: cpp
dist: bionic

branches:
  except: /pr\/.*/

compiler:
  - gcc
  - clang

os:
  - linux

arch:
  - amd64

addons:
  apt:
    update: true

install:
  - sudo apt update
  - sudo apt -y install gnuplot cmake g++-8 libstdc++-8-dev clang-10
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - sudo ln -s /usr/bin/clang-10 /usr/local/bin/clang
  - sudo ln -s /usr/bin/clang++-10 /usr/local/bin/clang++

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir build
  - cd $TRAVIS_BUILD_DIR/build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake --build .
  - DESTDIR=./install cmake -DCMAKE_INSTALL_PREFIX=/ -P ./cmake_install.cmake

after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - mkdir test
  - ./install/lab1/lab1 --dump-data -od test
  - |
    for file in ./install/lab1/output/*.txt; do
      diff "$file" "test/$(basename $file)"
    done
