notifications:
  email: false

language: cpp
dist: bionic

branches:
  except: /pr\/.*/

compiler:
  - gcc
  - clang

os:
  - linux

arch:
  - amd64

addons:
  apt:
    update: true

install:
  - sudo apt update
  - sudo apt -y install gnuplot cmake g++-8 libstdc++-8-dev clang-10
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - sudo ln -s /usr/bin/clang-10 /usr/local/bin/clang
  - sudo ln -s /usr/bin/clang++-10 /usr/local/bin/clang++

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir build
  - cd $TRAVIS_BUILD_DIR/build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake --build .
  - DESTDIR=./install cmake -DCMAKE_INSTALL_PREFIX=/ -P ./cmake_install.cmake
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/install/support/
  - cd $TRAVIS_BUILD_DIR/build/install/lab1
  - mkdir test
  - ./lab1 --dump-data -od test -o jpg
  - ./lab1 --dump-data --nonlinear -od test -o jpg
  - ls test
  - |
    for file in ./output/*.txt; do
      diff "$file" "./test/$(basename $file)"
    done
