language: c++
sudo: false
dist: bionic

branches:
  except: /pr\/.*/

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    update: true
    packages:
      - cmake
      - gnuplot

script:
  - (mkdir build && cd build)
  - cmake ..
  - cmake --build .
  - DESTDIR=./install cmake -DCMAKE_INSTALL_PREFIX=/ -P ./cmake_install.cmake

after_success:
  - cd ..
  - ./install/lab1/lab1 --dump-data -od test
  - |
    for file in ./install/lab1/output/*.txt; do
      diff "$filename" "test/$(basename $filename)"
    done
