language: c++
sudo: false
dist: bionic

branches:
  except: /pr\/.*/

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    - gnuplot
    update: true
    packages:
    - cmake

script:
  - . install_support.sh
  - ./install/lab1/lab1 --dump-data -od test
  - |
    for file in ./install/lab1/output/*.txt; do
      diff "$filename" "test/$(basename $filename)"
    done
